// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/0ffa9c0f32fba32f61a2516dd2438fad537ba577/ejson/ejson.d.ts
declare module "ejson" {
  interface StringifyOptions {
    canonical: boolean;
    indent: boolean|number|string;
  }

  interface CloneOptions {
    keyOrderSensitive: boolean;
  }
  
  function clone<T>(obj: T): T;
  function parse(str: string): any;
  function stringify(obj: any, options?: StringifyOptions): string;

  function toJSONValue(obj: any): string;
  function fromJSONValue(obj: string): any;
  function isBinary(value: any): boolean;
  function newBinary(len: number): Uint8Array;
  function equals(a: any, b: any, options?: CloneOptions): boolean;
}
